const characters = [
  "A brave knight",
  "A mischievous cat",
  "A robot from the future",
  "A wise old wizard",
  "A space explorer",
  "A pirate captain",
  "A superhero in disguise",
  "A friendly ghost",
  "A dragon",
  "A time-traveling teenager",
  "A curious alien",
  "A magical fairy",
  "A detective",
  "A Pocket Monster",
  "A talking tree",
  "A puppy",
  "A tiger cub",
  "A talking car",
  "A talking dinosaur",
  "Albert Einstein",
  "Marie Curie",
  "Leonardo da Vinci",
  "William Shakespeare",
  "Mona Lisa",
  "Sherlock Holmes",
  "Harry Potter",
  "Frodo Baggins",
  "Gandalf",
  "Elsa from Frozen",
  "Mickey Mouse",
  "Bugs Bunny",
  "Pocahontas",
  "Simba",
  "Pikachu",
  "Mario Bros",
  "Princess Zelda",
  "Don Quixote",
  "Sancho Panza",
  "Zorro",
  "Luke Skywalker",
  "Darth Vader",
  "Yoda",
  "Spock",
  "Captain Kirk",
  "Marty McFly",
  "Dr. Emmett Brown",
  "E.T. the Extra-Terrestrial",
  "Forrest Gump",
  "Rocky Balboa",
  "Charlie Chaplin",
  "Buster Keaton",
  "Audrey Hepburn",
  "Marilyn Monroe",
  "Elvis Presley",
  "Michael Jackson",
  "Freddie Mercury",
  "The Beatles",
  "Bob Dylan",
  "Madonna",
  "Elton John",
  "Stephen Hawking",
  "Galileo Galilei",
  "Isaac Newton",
  "Nikola Tesla",
  "Charles Darwin",
  "Wolfgang Amadeus Mozart",
  "Ludwig van Beethoven",
  "Frida Kahlo",
  "Pablo Picasso",
  "Vincent van Gogh",
  "Salvador Dalí",
  "The Little Prince",
  "Alice in Wonderland",
  "Cinderella",
  "Sleep Beauty",
  "Peter Pan",
  "Tinker Bell",
  "Tarzan",
  "Robin Hood",
  "Hercules",
  "Odysseus",
  "Homer Simpson",
  "Marge Simpson",
  "Bart Simpson",
  "SpongeBob SquarePants",
  "Shrek",
  "Puss in Boots",
  "Woody from Toy Story",
  "Buzz Lightyear",
  "Wall-E",
  "Tiana from The Princess and the Frog",
  "Mulan",
  "Moana",
  "Jack Sparrow",
  "Indiana Jones",
  "James Bond",
  "Harry Houdini",
  "Gandalf",
  "Neo from The Matrix",
  "Terminator",
  "RoboCop",
  "Godzilla",
  "King Kong",
  "Superman",
  "Batman",
  "Wonder Woman",
  "Spider-Man",
  "Iron Man",
  "Captain America",
  "The Flash",
  "Aquaman",
  "Thor",
  "Hulk",
  "Goku",
  "Vegeta",
  "Sailor Moon",
  "Hello Kitty",
  "Little Red Riding Hood",
  "The Big Bad Wolf",
  "The Little Mermaid",
  "Jasmine",
  "Aladdin",
  "The Genie",
  "Pinocchio",
  "Jack and the Beanstalk",
  "Snoopy",
  "Charlie Brown",
  "Garfield",
  "Hello Kitty",
  "Popeye the Sailor",
  "Donald Duck",
  "Goofy",
  "Pluto",
  "Sonic the Hedgehog",
  "Pac-Man",
  "Yoshi",
  "Socrates",
  "Plato",
  "Aristotle",
  "Cleopatra",
  "Julius Caesar",
  "Marco Polo",
  "Genghis Khan",
  "Joan of Arc",
  "Christopher Columbus",
  "George Washington",
  "Abraham Lincoln",
  "Benjamin Franklin",
  "Nelson Mandela",
  "Mahatma Gandhi",
  "Mother Teresa of Calcutta",
  "Stephen King",
  "J.K. Rowling",
  "Jane Austen",
  "Mark Twain",
  "Edgar Allan Poe",
  "Lewis Carroll",
  "Charles Dickens",
  "Ernest Hemingway",
  "Donatello from TMNT",
  "Raphael from TMNT",
  "Leonardo from TMNT",
  "Michelangelo from TMNT",
  "Pocahontas",
  "Tarzan",
  "Mulan",
  "Hercules",
  "Elsa from Frozen",
  "Anna from Frozen",
  "Olaf from Frozen",
  "Moana",
  "Rapunzel",
  "Merida",
  "Belle",
  "Ariel",
  "Cinderella",
  "Snow White",
  "Aurora"
];

const situations = [
    "Discovering a hidden treasure",
    "Lost in a magical forest",
    "Riding a bicycle on the moon",
    "Baking a giant cake",
    "Escaping from a maze",
    "Teaching a class of animals",
    "Building a sandcastle at the beach",
    "Having a picnic in the rain",
    "Competing in a dance contest",
    "Solving a mysterious puzzle",
    "Exploring an underwater city",
    "Flying a kite in a storm",
    "Having a tea party with stuffed animals",
    "Playing hide and seek in a library",
    "Going on a treasure hunt",
    "Discovering a secret garden",
    "Racing against a robot",
    "Having a snowball fight with friends",
    "Creating a new invention",
    "Building a robot",
    "Waking up on a floating island in the sky.",
    "Being the only customer in a magical bookstore that travels through time.",
    "Finding a treasure map written in the stars.",
    "Being transported to a forest where the trees whisper ancient stories.",
    "Discovering that your reflection in the mirror has a life of its own.",
    "Participating in a baking contest where ingredients appear by telekinesis.",
    "Being an explorer on a planet where everything is made of giant crystals.",
    "Receiving a letter from your future self with mysterious instructions.",
    "Finding yourself in a city where all buildings change shape every night.",
    "Having a conversation with a marble statue that comes to life.",
    "Being the gardener of a botanical garden where the flowers sing.",
    "Climbing a staircase that leads to a different galaxy.",
    "Being in charge of a lighthouse that illuminates portals to other worlds.",
    "Unlocking an old pocket watch that can freeze time for a minute.",
    "Riding a train that travels through a rainbow.",
    "Helping a small robot find its home in a scrapyard.",
    "Having the ability to see other people's dreams as if they were movies.",
    "Attending a music concert performed by nature itself.",
    "Discovering that your pet can talk, but only when no one else is around.",
    "Finding a door at the back of your closet that leads to a gem cave.",
    "Walking through a city where shadows have their own personalities.",
    "Being the conductor of an orchestra of instruments made of ice.",
    "Having a paintbrush that can make your drawings come to life.",
    "Getting trapped in an infinite library where every book is a universe.",
    "Finding a typewriter that predicts what you're going to write next.",
    "Helping a paper dragon fly for the first time.",
    "Being in charge of a phoenix egg about to hatch.",
    "Discovering a secret path that is only visible under moonlight.",
    "Sailing on a boat made of clouds over an ocean of stars.",
    "Being the only human at a birthday party for talking animals.",
    "Having the ability to hear the thoughts of plants.",
    "Waking up to find your house surrounded by a forest that wasn't there before.",
    "Working as a cartographer in a world where the map is constantly changing.",
    "Finding an ancient coin that allows you to understand all languages.",
    "Being a baker who can bake bread that tastes like happy memories.",
    "Finding yourself in a room where gravity changes with every step.",
    "Receiving a message in a bottle that is a thousand years old.",
    "Being the last traditional toy maker in an age of robots.",
    "Having the ability to create soap bubbles that contain small constellations.",
    "Encountering a mirror that shows your past.",
    "Walking through a market where products from different eras are sold.",
    "Being the fashion designer for an underwater kingdom.",
    "Discovering that your wristwatch can rewind time by ten seconds.",
    "Finding a secret garden where butterflies have glass wings.",
    "Being an art critic who evaluates paintings that move on their own.",
    "Waking up and realizing you can fly, but only when you're dreaming.",
    "Being in a coffee shop where the waiters are friendly robots.",
    "Living in a house that floats on water.",
    "Being the guardian of a library that protects forgotten stories.",
    "Having the ability to control the rain.",
    "Working in a toy store where the toys come to life at night.",
    "Finding a diary that writes itself.",
    "Being the driver of a bus that travels through time.",
    "Getting trapped in a candy machine that gives you candies of flavors you've never tasted.",
    "Walking through a city where the streets are made of crystal clear water.",
    "Being an explorer in search of the mythical Fountain of Youth.",
    "Having an invisible friend that only you can see.",
    "Being a film director who shoots movies in dreams.",
    "Discovering that the animals in your neighborhood can talk to you.",
    "Being at a music festival where the instruments float in the air.",
    "Being an archaeologist who excavates ruins of an alien civilization.",
    "Finding a lantern that lights the way to a fairy kingdom.",
    "Living in a world where people use magic instead of technology.",
    "Being the captain of a ship that can sail through space.",
    "Having the ability to control the weather.",
    "Discovering that your shadow can separate from you and have its own adventure.",
    "Being the owner of a store of magical gifts.",
    "Finding yourself in a forest where the leaves are banknotes.",
    "Being the guardian of a treasure that shines with its own light.",
    "Having the ability to communicate with the ghosts of inanimate objects.",
    "Walking through a park where the trees give fruits that cure any disease.",
    "Being a photographer who can capture people's memories in photos.",
    "Finding a path that is only visible if you are barefoot.",
    "Being the only human in a land of friendly giants.",
    "Having the ability to revive people's memories with a touch.",
    "Living in a world where the clouds are animals.",
    "Being in charge of a garden of flowers that change color according to your mood.",
    "Discovering that your favorite book has a different ending every time you read it.",
    "Being the only human in a land of talking animals.",
    "Having the ability to create small universes inside bottles.",
    "Being in a theater where the play creates itself.",
    "Being an explorer in search of Atlantis.",
    "Finding a clock that can rewind time for everyone, not just for you.",
    "Having the ability to make inanimate objects come to life for a short period of time.",
    "Living in a world where the sky is full of planets.",
    "Being in charge of a museum where the exhibits change every day.",
    "Discovering that your home is the headquarters of a superhero team.",
    "Being the only human in a world of robots.",
    "Having the ability to read the minds of animals.",
    "Walking through a forest where the trees are made of crystal.",
    "Being in charge of a lighthouse that illuminates a path to the moon.",
    "Finding an object that allows you to make a wish.",
    "Living in a world where people can fly.",
    "Being the guardian of a floating island.",
    "Having the ability to communicate with the moon.",
    "Walking through a garden where the flowers are made of metal.",
    "Being in charge of a library where the books are portals to other worlds.",
    "Finding a path that is only visible at night.",
    "Being the only human in a land of mythical creatures.",
    "Having the ability to make people's dreams come true.",
    "Living in a world where the sky is full of shooting stars.",
    "Being in charge of a museum where the exhibits are living beings.",
    "Discovering that your shadow can talk.",
    "Being the only human in a land of friendly ghosts.",
    "Having the ability to create objects out of thin air.",
    "Walking through a forest where the leaves are gold.",
    "Being in charge of a lighthouse that illuminates a path to your dream home.",
    "Finding an object that allows you to travel to the past.",
    "Living in a world where the sky is full of rainbows.",
    "Being the guardian of an island that moves.",
    "Having the ability to talk to the dead.",
    "Walking through a garden where the flowers are made of glass.",
    "Being in charge of a library where the books are made of paper.",
    "Finding a path that is only visible under water.",
    "Being the only human in a land of giants.",
    "Having the ability to create life.",
    "Living in a world where the sky is full of colored clouds.",
    "Being in charge of a museum where the exhibits are objects from your dreams.",
    "Discovering that your reflection can come out of the mirror.",
    "Being the only human in a land of friendly robots.",
    "Having the ability to control fire.",
    "Walking through a forest where the trees are made of silver.",
    "Being in charge of a lighthouse that illuminates a path to a fantasy world.",
    "Finding an object that allows you to travel to the future.",
    "Living in a world where the sky is full of comets.",
    "Being the guardian of an island that is invisible.",
    "Having the ability to read people's minds.",
    "Walking through a garden where the flowers are made of liquid metal.",
    "Being in charge of a library where the books are made of crystal.",
    "Finding a path that is only visible with your eyes closed.",
    "Being the only human in a land of mythological creatures.",
    "Having the ability to create miniature universes.",
    "Living in a world where the sky is full of colored planets.",
    "Being in charge of a museum where the exhibits are your own memories.",
    "Discovering that your shadow has a life of its own.",
    "Being the only human in a land of ghosts.",
    "Having the ability to make inanimate objects come to life.",
    "Walking through a forest where the trees are made of chocolate.",
    "Being in charge of a lighthouse that illuminates a path to a sci-fi world.",
    "Finding an object that allows you to travel to another universe.",
    "Living in a world where the sky is full of colored stars.",
    "Being the guardian of an island that floats in space.",
    "Having the ability to talk to ghosts.",
    "Walking through a garden where the flowers are made of fire.",
    "Being in charge of a library where the books are made of light.",
    "Finding a path that is only visible in the dark.",
    "Being the only human in a land of dragons.",
    "Having the ability to make your drawings come to life.",
    "Living in a world where the sky is full of suns.",
    "Being in charge of a museum where the exhibits are your own creations.",
    "Discovering that your reflection can talk.",
    "Being the only human in a land of fairies.",
    "Having the ability to create soap bubbles that contain universes.",
    "Walking through a forest where the trees are made of candy.",
    "Being in charge of a lighthouse that illuminates a path to a dream world.",
    "Finding an object that allows you to travel to your own past.",
    "Living in a world where the sky is full of moons.",
    "Being the guardian of an island that is a living being.",
    "Having the ability to talk to animals.",
    "Walking through a garden where the flowers are made of colored glass.",
    "Being in charge of a library where the books are made of sand.",
    "Finding a path that is only visible through your dreams."

];

function getRandomItem(arr) {
    return arr[Math.floor(Math.random() * arr.length)];
}

document.getElementById('characterBtn').addEventListener('click', function() {
    document.getElementById('characterPrompt').textContent = getRandomItem(characters);
});

document.getElementById('situationBtn').addEventListener('click', function() {
    document.getElementById('situationPrompt').textContent = getRandomItem(situations);
});


function getRandomBGColor() {
    const letters = '0123456789ABCDEF';
    let color = '#';
    for (let i = 0; i < 6; i++) {
        color += letters[Math.floor(Math.random() * 16)];
    }
    return color;
}


const gradientArr = [
    'linear-gradient(120deg, #f6d365 0%, #fda085 100%)',
    'linear-gradient(120deg, #84fab0 0%, #8fd3f4 100%)',
    'linear-gradient(120deg, #a1c4fd 0%, #c2e9fb 100%)',
    'linear-gradient(120deg, #fbc2eb 0%, #a6c1ee 100%)',
    'linear-gradient(120deg, #fccb90 0%, #d57eeb 100%)',
    'linear-gradient(120deg, #f093fb 0%, #f5576c 100%)',
    'linear-gradient(120deg, #f6d365 0%, #fda085 100%)',
    'linear-gradient(120deg, #fdfbfb 0%, #ebedee 100%)',
    'linear-gradient(120deg, #fdfbfb 0%, #ebedee 100%)',
    'linear-gradient(120deg, #f6d365 0%, #fda085 100%)',
    'linear-gradient(120deg, #a1c4fd 0%, #c2e9fb 100%)',
    'linear-gradient(120deg, #84fab0 0%, #8fd3f4 100%)',
    'linear-gradient(120deg, #fbc2eb 0%, #a6c1ee 100%)',
    'linear-gradient(120deg, #fccb90 0%, #d57eeb 100%)',
    'linear-gradient(120deg, #f093fb 0%, #f5576c 100%)',
]

function setRandomBackground() {
    //const randomColor = getRandomBGColor();
    //document.body.style.backgroundColor = randomColor;
    const randomGradient = gradientArr[Math.floor(Math.random() * gradientArr.length)];
    document.body.style.background = randomGradient;    
}

window.onload = setRandomBackground;

